services:
  app:
    build:
      context: .
      target: development
    container_name: osrs-otk-dev
    ports:
      - "8080:8080"
      - "5173:5173"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend  
      - ./.air.toml:/app/.air.toml
      - node_modules:/app/frontend/node_modules
    environment:
      - APP_ENV=docker
      - CGO_ENABLED=0
      - VITE_API_BASE_URL=http://localhost:8080
    working_dir: /app
    command: /app/scripts/docker-start-dev.sh
    restart: unless-stopped

volumes:
  node_modules: