services:
  # Unified development service (simpler approach)
  app:
    build:
      context: .
      target: development
    container_name: osrs-otk-dev
    ports:
      - "8080:8080"
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/web/frontend/node_modules  # Prevent node_modules overwrite
      - go_modules:/go/pkg/mod                       # Cache Go modules
    environment:
      - APP_ENV=docker
      - CGO_ENABLED=0
      - VITE_API_BASE_URL=http://localhost:8080
    working_dir: /app
    command: /app/scripts/docker-start-dev.sh
    networks:
      - osrs-network
    restart: unless-stopped

networks:
  osrs-network:
    driver: bridge

volumes:
  node_modules:
  go_modules: