server:
  port: "8080"
  host: "0.0.0.0"  # Bind to all interfaces for Docker

assets:
  skill_data_path: "assets/data/skills"
  images_path: "assets/images"

cors:
  allowed_origins:
    - "http://localhost:5173"
    - "http://localhost:3000"
    - "http://localhost:80"
    - "http://localhost"
  allowed_methods:
    - "GET"
    - "POST"
    - "OPTIONS"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Accept"
    - "Content-Type"
    - "Content-Length"
    - "Accept-Encoding"
    - "Authorization"
    - "X-CSRF-Token"
    - "X-Requested-With"