server:
  port: "8080"
  host: "0.0.0.0"

assets:
  skill_data_path: "assets/data/skills"
  images_path: "assets/images"

cors:
  allowed_origins:
    - "https://your-frontend-domain.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "OPTIONS"
  allowed_headers:
    - "Accept"
    - "Content-Type"
    - "Content-Length"
    - "Accept-Encoding"